#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
    apt install $OTHER_INSTALLS -y
   fi
   }
_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
   }
    
apt update && apt upgrade -y
apt install git -y
_other_installs
pip3 install -U pip
git clone -b heroku $REPO_URL Repo
rm Procfile
rm requirements.txt
rm README.md
mv Repo/* .
pip3 install -U -r requirements.txt
_externals
gunicorn Api.main:app --timeout 100 --log-file=-
