#!/bin/bash

apt update && apt upgrade -y
apt install git -y
pip3 install -U pip
git clone -b main $URL Skye
rm Procfile
rm requirements.txt
rm README.md
mv Skye/* .
pip3 install -U -r requirements.txt
python3 -m DezAlty
